#!/bin/bash
source ${SCRIPT_DIR}/config/base_config

AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
B2_BUCKET_NAME=""

RESTIC_REPOSITORY="s3:s3.us-east-005.backblazeb2.com/${B2_BUCKET_NAME}"
RESTIC_PASSWORD=""

RESTIC_SOURCE="/data/www/mediawiki"

RESTIC_FORGET_OPTIONS="--prune --repack-cacheable-only --keep-within=7d1h"
RESTIC_BACKUP_OPTIONS="--one-file-system --limit-upload=20000 --verbose=3"

GOMAXPROCS=4
